//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filippov.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dogovor
    {
        public int Id { get; set; }
        public string Id_custumer { get; set; }
        public string Id_employee { get; set; }
        public int Id_strah_sluchai { get; set; }
        public Nullable<int> Id_strah_type { get; set; }
        public decimal Tarif { get; set; }
        public decimal Strah_summa { get; set; }
        public decimal Strah_platej { get; set; }
        public System.DateTime Date_start { get; set; }
        public System.DateTime Date_end { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual Strah_sluchai Strah_sluchai { get; set; }
        public virtual Strah_type Strah_type { get; set; }
    }
}
